### ISSUE TITLE
Finding 12 character prefix collision

### ISSUE THREAD

**Issue by kees** [not-an-aardvark/lucky-commit#36]
Hi!

I tried to find a 12 character prefix collision but lucky_commit exhausted the search space. (This took about 7 hours on an RTX 3080.) If I'm reading lib.rs correctly, this is because "only" 48 bytes (a single dynamic block) are being mutated? I was thinking I could raise the search space from 48 to 96 to add another dynamic block but ended up getting stumped. Is it possible to expand the search space? Or add more characters to the whitespace set (like \r, \n, maybe \v and \f)?

**Comment by kees** [comment]
Specifically where I got stumped was that `dynamic_padding_mut` and `scatter_padding_and_find_match` operate only on `dynsmic_blocks[0]`. (Though the latter also hashes 1..num_dynamic_blocks?)

**Comment by not-an-aardvark** [comment]
To provide some background, there are a few reasons that the 48-bit search space is hardcoded:

- Using 48 bytes of dynamic padding allows the hash data to only contain one dynamic block in a majority of cases. The hashing time is directly proportional to the number of dynamic blocks, so switching to a 96-bit search space (or even a 72-bit search space) would typically double the amount of time that it takes to find a match for any given prefix.
    - Git commits typically have a trailing newline. To avoid interfering with formatting, all the padding is inserted before the newline. There's also 8 bytes of padding added by the sha1 format. So to fit all the dynamic padding + the end of the commit into the last 64-byte block, we could have at most 55 bytes of dynamic padding. I chose 48 bytes since it's a multiple of 8, which [probably helps with the performance of writing to the padding](https://github.com/not-an-aardvark/lucky-commit/blob/00000002877d35de410890b322e3f76790706390/src/lib.rs#L676-L685), although admittedly I didn't benchmark it against the alternative.
- I feel like there are diminishing returns on brute-forcing longer and longer shorthashes. IMO the main "interesting" use cases of the tool are (a) colliding with Git's default-length shorthashes (7-character prefix, although it can go a bit higher in large repos) and (b) theoretically colliding with a full-length 40-character hash (which isn't feasible regardless of the implementation strategy). Between those two extremes, it seems like there are proof-of-work blockchains and not much else. I don't want someone to use my tool to create a proof-of-work blockchain within a git repository, that would be silly and wasteful. (This tool is already kind of silly, but it's not that wasteful.)

Anyway, if you want to create a 12-character prefix collision, I think there are a few options (in increasing order of difficulty):

- You could manually amend the commit with a trivial change (e.g. changing the timestamp) and try running the tool again. For a 12-character prefix, your odds of finding a match in the entire 48-bit search space are around (1-1/e) ~= 63%. So you got slightly unlucky the first time, but the odds are still pretty good if you reroll.
- You could try forking/patching the tool to use e.g. 56 bytes of dynamic padding rather than 48. I think things would basically still work with 56 bytes, although to preserve performance you would want to ensure that the trailing newline is before the dynamic padding rather than [after](https://github.com/not-an-aardvark/lucky-commit/blob/00000002877d35de410890b322e3f76790706390/src/lib.rs#L586). (You would also need to tweak the OpenCL code a bit, e.g. [this part](https://github.com/not-an-aardvark/lucky-commit/blob/00000002877d35de410890b322e3f76790706390/src/sha1_matcher.cl#L45-L62) assumes that there are exactly 48 dynamic padding bytes.)
- You could change how a "padding specifier" is serialized into a commit message (using additional characters beyond spaces and tabs, as you suggested), allowing you to fit more entropy into the 48-bit search space. You could do this by editing [`scatter_padding`](https://github.com/not-an-aardvark/lucky-commit/blob/00000002877d35de410890b322e3f76790706390/src/lib.rs#L659) and making the equivalent edits to [`scatter_padding_and_find_match`](https://github.com/not-an-aardvark/lucky-commit/blob/00000002877d35de410890b322e3f76790706390/src/sha1_matcher.cl#L12). I don't think this would break anything for non-GPG-signed commits. For GPG-signed commits, you would probably want to avoid `\n`, since git interprets `\n\n` as the end of the commit metadata and the start of the commit message. Other whitespace characters might work (without affecting the validity of the GPG signature), but I haven't tested them. You would still be limited to 64 bits of entropy due to some things that are stored as `u64`.
- You could increase the search space to larger than 64 bits. There's nothing fundamentally impossible here, but it would be a larger refactoring because some parts of the code assume that things can be represented in a 64-bit integer.

**Comment by kees** [comment]
Thanks for such a thoughtful reply!

I tried your first suggestion, and tweaked the commit date/time and got a 12-char collision in under a half an hour, so apparently I have touched both ends of the luck spectrum now. :)

Thanks!
